library 'cb-days@tf-overhaul'
def testPodYaml = libraryResource 'podtemplates/vuejs/vuejs-test-pod.yml'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '10'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 10)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
  }
  stages('VueJS Test and Build')
  {
    stage('VueJS Tests') {
      agent {
        kubernetes {
          label 'nodejs'
          yaml testPodYaml
       }
      }
      steps {
            checkout scm           
            container('nodejs') {
              sh '''
                 yarn install
                 yarn test:unit
                 '''
            }
      } 
    }
    stage('Build and Push Image') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps { 
        kanikoBuildPushGeneric("microblog-frontend", "latest", "${gcpProject}/${repoOwner}")
        {
          checkout scm
        }
      }
    } 
  }
  post {
    success {
      node{
      cloudBeesFlowTriggerRelease configuration: 'ThunderCDEnv', parameters: '{"release":{"releaseName":"Wroble 2020.10.06","stages":[{"stageName":"Post Prod","stageValue":""},{"stageName":"Pre-Prod","stageValue":""},{"stageName":"Prod","stageValue":""},{"stageName":"Quality Assurance (QA)","stageValue":""},{"stageName":"Release Readiness","stageValue":""}],"pipelineName":"Wroble 2020.10.06","parameters":[{"parameterName":"FE-Build-number","parameterValue":"1.1.3"},{"parameterName":"BE-Build-number","parameterValue":"1.0.2"},{"parameterName":"microblog-backend_version","parameterValue":""},{"parameterName":"microblog-frontend_version","parameterValue":""},{"parameterName":"microblog-db_version","parameterValue":"12.1-alpine"}]}}', projectName: 'cwroble Demo', releaseName: 'Wroble 2020.10.06', startingStage: 'Release Readiness'
    }
    }
  }
    }

