library 'cb-days@onprem'
def hugoPodYaml = libraryResource 'podtemplates/hugo/pod.yml'
def cloudRunYaml = libraryResource 'podtemplates/cloud-run.yml'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 2)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
  }
  stages {
    stage('Master build & deploy') {
      agent {
        kubernetes {
          label 'hugo-builder'
          yaml hugoPodYaml
        }
      }
      when {
        beforeAgent true
        branch 'master'
      }
      stages {
        stage("Build site") {
          steps {
            checkout scm
            container('hugo') {
              sh "hugo"
              stash name: "public", includes: "public/**"
            }
          }
        }
        // stage("Build and push image") {
        //   steps {
        //     kanikoBuildPushGeneric("${projectName}", "master-${env.BUILD_NUMBER}", "${gcpProject}"){
        //       checkout scm
        //       unstash "public"
        //     }
        //   }
        // }
        stage("Build and push image") {
          steps {
            echo "Build and push image to registry."
          }
        }
        stage("Deploy to preview env") {
          steps {
            withCredentials([string(credentialsId: 'cluster', variable: 'KUBECONFIG')]) {
              cloudRunDeploy(serviceName: "${projectName}", image: "docker.io/ldonleycb/test-blog:latest", deployType: "${deployTypeMaster}", region: "${gcpRegionMaster}", clusterName: "${clusterNameMaster}", namespace: "${namespaceMaster}", kubeconfig: "$KUBECONFIG")
            }
          }
        }
      }
    }   
  }
}
