library 'cb-days@GA-Rollout'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 2)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
  }
  stages {
    stage('Build and Push Image') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps { 
        script{
          echo("Pre rolloutKanikoBuildPush #1")
          rolloutKanikoBuildPush("rolloutjs", env.IMAGE_TAG, "${gcpProject}") {
            checkout scm
          }
          // echo("Pre rolloutKanikoBuildPush #2")
          // rolloutKanikoBuildPush("rolloutjava", env.IMAGE_TAG, "${gcpProject}") {
          //   checkout scm
          // }
        }
      }
    }
    stage('Deploy') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps {
        script{
          echo("rolloutKubeDeploy #1")
          rolloutKubeDeploy("rolloutjs", env.IMAGE_TAG, "${githubCredentialId}", "${repoOwner}")
          // echo("rolloutKubeDeploy #2")
          // rolloutKubeDeploy("rolloutjava", env.IMAGE_TAG, "${githubCredentialId}", "${repoOwner}")
        } 
      }
    }   
  }
}
